# This workflow integrates Qwiet preZero with GitHub and exports SARIF results to the Security Tab
name: QwietAFPRnBR

on:
  pull_request:
  workflow_dispatch:

permissions:
  security-events: write  # Ensure proper permissions to upload SARIF results

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK v11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Download Qwiet CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: preZero NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --verbose --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} ./..
      
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
